- id: '1598726114260'
  alias: Garage Door Close if Open
  description: ''
  trigger:
  - entity_id: scene.gdlnta2yonphwyhh
    for: 0:05:00
    platform: state
    to: 'True'
  condition: []
  action:
  - data: {}
    entity_id: scene.0f4bmmtdbgehxkp9
    service: scene.turn_on
  mode: single
- id: '1599182935537'
  alias: Kitchen Leak Sensor Wet
  description: ''
  trigger:
  - device_id: 81603e0c094d4158b29605ed1a7396c8
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_leak_sensor_water
    platform: device
    type: moist
  condition: []
  action:
  - data:
      message: Kitchen leak sensor is wet
    service: persistent_notification.create
  - data:
      message: Kitchen leak sesor is wet
    service: notify.notify
  mode: single
- id: '1599183199313'
  alias: Leak Sensor Battery
  description: ''
  trigger:
  - below: 25
    device_id: 81603e0c094d4158b29605ed1a7396c8
    domain: sensor
    entity_id: sensor.kitchen_leak_sensor_battery
    platform: device
    type: battery_level
  condition: []
  action:
  - data:
      message: Leak Sensor Battery Low
    service: persistent_notification.create
  mode: single
- id: '1599415392223'
  alias: Leak Sensor SMS
  description: ''
  trigger:
  - device_id: 81603e0c094d4158b29605ed1a7396c8
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_leak_sensor_water
    platform: device
    type: moist
  condition: []
  action:
  - data:
      message: Water sensor is wet
      target: '+18155292638'
    service: notify.ha_twillio
  mode: single
- id: '1599510095098'
  alias: Turn off AC and open windows
  description: ''
  trigger:
  - entity_id: binary_sensor.warm_inside
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: device
    device_id: 28cb21d2dd5e471f8a6a1bdfb963126e
    domain: climate
    entity_id: climate.bedroom_2
    hvac_mode: cool
    type: is_hvac_mode
  - after: sunrise
    after_offset: '1:00:00'
    condition: sun
  - before: '22:00:00'
    condition: time
  action:
  - data:
      message: Turn off the AC and consider opening the windows tonight
    service: persistent_notification.create
  - data:
      message: Turn off the AC and consider opening the windows tonight
    service: notify.notify
  mode: single
- id: '1599510701899'
  alias: Close windows
  description: ''
  trigger:
  - entity_id: binary_sensor.cool_inside
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: sun
    after: sunrise
  - condition: template
    value_template: "{{\n  is_state('binary_sensor.dinning_room_door', 'on') or\n\
      \  is_state('binary_sensor.master_bedroom_door_and_window', 'on') or\n  is_state('binary_sensor.bedroom_window',\
      \ 'on') or\n  is_state('binary_sensor.office_window', 'on') or\n  is_state('binary_sensor.living_room',\
      \ 'on')\n}}\n"
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.close_windows.attributes.last_triggered)
      | int > 7200 }}'
  - condition: template
    value_template: '{{ states.automation.close_windows.attributes.last_triggered
      == none }}'
  action:
  - data:
      message: Time to close the windows to keep the house cool.
    service: notify.notify
  - data:
      message: Time to close the windows to keep the house cool.
    service: persistent_notification.create
  - data:
      message: Time to close the windows to keep the house cool.
      target:
      - '+18155292638'
      - '+18155297819'
      - '+18157012174'
    service: notify.ha_twillio
  initial_state: true
  mode: single
- id: '1599511189810'
  alias: Open Windows
  description: ''
  trigger:
  - entity_id: binary_sensor.warm_inside
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    condition: sun
  - before: '22:00'
    condition: time
  - condition: template
    value_template: '{{is_state(''binary_sensor.living_room'', ''off'')}}'
  action:
  - data:
      message: Open the windows - it's cooler outside.
    service: persistent_notification.create
  - data:
      message: Open the windows - it's cooler outside.
    service: notify.notify
  - data:
      message: Open the windows - it's cooler outside.
      target:
      - '+18155292638'
      - '+18155297819'
      - '+18157012174'
    service: notify.ha_twillio
  initial_state: true
  mode: single
- id: '1599954800487'
  alias: Notify me if the door opens
  description: ''
  trigger:
  - device_id: e8dbf5f4cb464beea9b0704c9dd38b76
    domain: binary_sensor
    entity_id: binary_sensor.entry_exit_doors
    platform: device
    type: opened
  condition: []
  action:
  - device_id: e8dbf5f4cb464beea9b0704c9dd38b76
    domain: switch
    entity_id: switch.konnected_piezo_alarm
    type: toggle
  mode: single
- id: '1630190606849'
  alias: Tablet Outlet - On-Off
  description: Tablet Outlet - On-Off schedule with state persistence
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      off_time: '22:00:00'
      on_time: '5:00:00'
      automation_target:
        device_id: 1172a94fe757637e68fd1370cd66f956
- id: '1630190917215'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.persistent_notification
        data:
          message: '{{sensors}} battery is low.'
- id: '1636235518164'
  alias: Patio Outlet - Toggle
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fa5c6864b903aa221bab51b9a6d50cb9
    type: action
    subtype: single
    discovery_id: 0x00158d0006fbadb8 action_single
  condition: []
  action:
  - type: toggle
    device_id: 91e0e8ef4d1bb7304ca42282a613b7b9
    entity_id: switch.patio_outlet
    domain: switch
  mode: single
- id: '1636318358363'
  alias: Misters Outlet - Toggle
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: feacb8f4e4907f70db0cc4e7b3e3e6aa
    type: action
    subtype: single
    discovery_id: 0x00158d0006f3a455 action_single
  condition: []
  action:
  - type: toggle
    device_id: a0179854428aa5bc736656e48848be32
    entity_id: switch.patio_mister_outlet
    domain: switch
  mode: single
- id: '1636608738706'
  alias: Overnight Outlets Off-On
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      off_time: '23:30:00'
      on_time: 09:00:00
      automation_target:
        device_id:
        - bcb86309d2fa3856e42ccc4e023c0901
        - 91e0e8ef4d1bb7304ca42282a613b7b9
        - c78075d1bfd6a491cb01eccd7c7d05ac
        - de3fee10eb91b4c209f2d4f0bdccb6c3
      trigger_at_homeassistant_startup: true
- id: mqtt_garage_door_status
  alias: 'MQTT Garage Door Status'
  trigger:
    platform: state
    entity_id: binary_sensor.double_garage_door_contact
  action:
  - service: mqtt.publish
    data_template:
      topic: 'home-assistant/garage/state'
      payload_template: "{{ 'open' if states.binary_sensor.double_garage_door_contact.state =='on' else 'closed' }}"
      retain: true
      
- id: mqtt_shelly_announce
  alias: Shelly Sync at HA Start
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:00:20
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce

