- id: '1599182935537'
  alias: Kitchen Leak Sensor Wet
  description: ''
  trigger:
  - device_id: 81603e0c094d4158b29605ed1a7396c8
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_leak_sensor_water
    platform: device
    type: moist
  condition: []
  action:
  - data:
      message: Kitchen leak sensor is wet
    service: persistent_notification.create
  - data:
      message: Kitchen leak sesor is wet
    service: notify.notify
  mode: single
- id: '1599415392223'
  alias: Leak Sensor SMS
  description: ''
  trigger:
  - device_id: 81603e0c094d4158b29605ed1a7396c8
    domain: binary_sensor
    entity_id: binary_sensor.kitchen_leak_sensor_water
    platform: device
    type: moist
  condition: []
  action:
  - data:
      message: Water sensor is wet
      target: '+18155292638'
    service: notify.ha_twillio
  mode: single
- id: '1599510095098'
  alias: Turn off AC and open windows
  description: ''
  trigger:
  - entity_id: binary_sensor.warm_inside
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: device
    device_id: 28cb21d2dd5e471f8a6a1bdfb963126e
    domain: climate
    entity_id: climate.bedroom_2
    hvac_mode: cool
    type: is_hvac_mode
  - after: sunrise
    after_offset: '1:00:00'
    condition: sun
  - before: '22:00:00'
    condition: time
  action:
  - data:
      message: Turn off the AC and consider opening the windows tonight
    service: persistent_notification.create
  - data:
      message: Turn off the AC and consider opening the windows tonight
    service: notify.notify
  mode: single
- id: '1599510701899'
  alias: Close windows
  description: ''
  trigger:
  - entity_id: binary_sensor.cool_inside
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: sun
    after: sunrise
  - condition: template
    value_template: "{{\n  is_state('binary_sensor.dinning_room_door', 'on') or\n
      \ is_state('binary_sensor.master_bedroom_door_and_window', 'on') or\n  is_state('binary_sensor.bedroom_window',
      'on') or\n  is_state('binary_sensor.office_window', 'on') or\n  is_state('binary_sensor.living_room',
      'on')\n}}\n"
  - condition: template
    value_template: '{{ as_timestamp(now()) - as_timestamp(states.automation.close_windows.attributes.last_triggered)
      | int > 7200 }}'
  - condition: template
    value_template: '{{ states.automation.close_windows.attributes.last_triggered
      == none }}'
  action:
  - data:
      message: Time to close the windows to keep the house cool.
    service: notify.notify
  - data:
      message: Time to close the windows to keep the house cool.
    service: persistent_notification.create
  - data:
      message: Time to close the windows to keep the house cool.
      target:
      - '+18155292638'
      - '+18155297819'
      - '+18157012174'
    service: notify.ha_twillio
  initial_state: true
  mode: single
- id: '1599511189810'
  alias: Open Windows
  description: ''
  trigger:
  - entity_id: binary_sensor.warm_inside
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    condition: sun
  - before: '22:00'
    condition: time
  - condition: template
    value_template: '{{is_state(''binary_sensor.living_room'', ''off'')}}'
  action:
  - data:
      message: Open the windows - it's cooler outside.
    service: persistent_notification.create
  - data:
      message: Open the windows - it's cooler outside.
    service: notify.notify
  - data:
      message: Open the windows - it's cooler outside.
      target:
      - '+18155292638'
      - '+18155297819'
      - '+18157012174'
    service: notify.ha_twillio
  initial_state: true
  mode: single
- id: '1599954800487'
  alias: Notify me if the door opens
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: e8dbf5f4cb464beea9b0704c9dd38b76
    entity_id: binary_sensor.entry_and_exit_doors
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: 52da387cc64bba0f27edf604e2fa754b
    entity_id: binary_sensor.kitchen_door_contact
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: 6053c3591b855fa8b50ac0c2da1a3ea8
    entity_id: binary_sensor.double_garage_door_contact
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: 5a414d40d78736993ccf16c5e02c03bf
    entity_id: binary_sensor.single_garage_door_contact
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: e8dbf5f4cb464beea9b0704c9dd38b76
    entity_id: binary_sensor.living_room_slider
    domain: binary_sensor
  - type: opened
    platform: device
    device_id: e8dbf5f4cb464beea9b0704c9dd38b76
    entity_id: binary_sensor.master_bedroom_sliding_door_and_window
    domain: binary_sensor
  condition: []
  action:
  - device_id: e8dbf5f4cb464beea9b0704c9dd38b76
    domain: switch
    entity_id: switch.konnected_piezo_alarm
    type: toggle
  mode: single
- id: '1630190917215'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      actions:
      - service: notify.persistent_notification
        data:
          message: '{{sensors}} battery is low.'
- id: '1636235518164'
  alias: Patio Outlet - Toggle
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: fa5c6864b903aa221bab51b9a6d50cb9
    type: action
    subtype: single
    discovery_id: 0x00158d0006fbadb8 action_single
  condition: []
  action:
  - type: toggle
    device_id: 91e0e8ef4d1bb7304ca42282a613b7b9
    entity_id: switch.patio_outlet
    domain: switch
  mode: single
- id: '1636318358363'
  alias: Misters Outlet - Toggle
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: feacb8f4e4907f70db0cc4e7b3e3e6aa
    type: action
    subtype: single
    discovery_id: 0x00158d0006f3a455 action_single
  condition: []
  action:
  - type: toggle
    device_id: a0179854428aa5bc736656e48848be32
    entity_id: switch.patio_mister_outlet
    domain: switch
  mode: single
- id: '1636608738706'
  alias: Overnight Outlets Off-On
  description: ''
  use_blueprint:
    path: EPMatt/on_off_schedule_state_persistence.yaml
    input:
      off_time: '23:59:00'
      on_time: 09:00:00
      automation_target:
        device_id:
        - bcb86309d2fa3856e42ccc4e023c0901
        - 91e0e8ef4d1bb7304ca42282a613b7b9
        - c78075d1bfd6a491cb01eccd7c7d05ac
        - de3fee10eb91b4c209f2d4f0bdccb6c3
        - 0039dd29816412a7480c21bf96b2311c
      trigger_at_homeassistant_startup: true
- id: mqtt_garage_door_status
  alias: MQTT Garage Door Status
  trigger:
    platform: state
    entity_id: binary_sensor.double_garage_door_contact
  action:
  - service: mqtt.publish
    data_template:
      topic: homeassistant/garage/state
      payload_template: '{{ ''open'' if states.binary_sensor.double_garage_door_contact.state
        ==''on'' else ''closed'' }}'
      retain: true
- id: mqtt_shelly_announce
  alias: Shelly Sync at HA Start
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:00:20
  - service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: b8aa033f-800f-4d26-8f99-f533d705421f
  alias: "[\U0001F4E3] Notify when garage door was left open for too long"
  trigger:
  - platform: state
    entity_id:
    - cover.garage_door
    to: open
    for:
      hours: 0
      minutes: 15
      seconds: 0
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.garage_door
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: notify.notify
    data:
      title: "\U0001F699 Garage left open!"
      message: Garage door has been open for 15 minutes. Close it?
  - service: tts.google_translate_say
    data:
      message: Garage door has been open for 15 minutes.
      entity_id: media_player.indoor_speakers
  - service: notify.ha_twillio
    data:
      message: Garage door has been open for 15 minutes. Close it?
      target:
      - '+18155292638'
      - '+18155297819'
  - service: timer.start
    data:
      duration: '15'
    target:
      entity_id: timer.garage_door
- id: '1646278519431'
  alias: Front Door Motion to Living Room TV
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 117d653311e2ec12bef6b585bc7f9a29
    entity_id: binary_sensor.camera6_front_door_motion
    domain: binary_sensor
  condition:
  - condition: time
    before: '23:00:00'
    after: 06:00:00
  - condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.wind_speed
      below: '5'
  action:
  - service: media_player.select_source
    data:
      source: Chromecast
    target:
      device_id:
      - 18cbba96da76862a2509ba42946eafa1
  - service: media_player.play_media
    target:
      entity_id: media_player.living_room_tv
    data:
      media_content_id: media-source://camera/camera.camera6_front_door
      media_content_type: application/vnd.apple.mpegurl
    metadata:
      title: Camera 6 - Front Door
      thumbnail: /api/camera_proxy/camera.camera6_front_door
      media_class: video
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://camera
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: media_player.turn_off
    data: {}
    target:
      entity_id:
      - media_player.living_room_tv
  - service: media_player.turn_off
    data: {}
    target:
      device_id:
      - 18cbba96da76862a2509ba42946eafa1
      - f625b0ace9d363f8adba50c62e78471f
  mode: parallel
- id: '1652032341234'
  alias: Water Softener Level Low
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 73cb9fef06de261a7786697780cdb740
    entity_id: sensor.water_softener
    domain: sensor
    above: 22
    for:
      hours: 1
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: Softener salt low. Buy 80 lbs water softener salt.
  mode: single
- id: '1653872562603'
  alias: Turn on at Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - type: turn_on
    device_id: d7a802679c81049ee90bb2651e396fc0
    entity_id: switch.pool_light
    domain: switch
  mode: single
- id: '1653879586582'
  alias: Turn off at 10:30 PM
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: d7a802679c81049ee90bb2651e396fc0
    entity_id: switch.pool_light
    domain: switch
  - type: turn_off
    device_id: 58eb5e43ca7528aa407d808560975814
    entity_id: switch.kitchen_tv_and_computer_outlet
    domain: switch
  mode: single
- id: '1655668385533'
  alias: Turn on at 6 AM
  description: ''
  trigger:
  - platform: time
    at: 06:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 58eb5e43ca7528aa407d808560975814
    entity_id: switch.kitchen_tv_and_computer_outlet
    domain: switch
  mode: single
- id: '1657990283413'
  alias: Alert when outside temperature isn't updating
  description: ''
  use_blueprint:
    path: Mr-Groch/offline-notification-for-sensors-with-last_seen.yaml
    input:
      hours: 1
      exclude:
        entity_id:
        - sensor.outside_temperature
      actions:
      - service: notify.persistent_notification
        data:
          message: Outside temperature nit reporting
- id: '1658687930209'
  alias: Garage Bench Light
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.garage_motion_occupancy
      target_entity: switch.garage_bench_light
      no_motion_wait: '2'
- id: '1658707653745'
  alias: Garage Overhead Light
  description: ''
  use_blueprint:
    path: freakshock88/motion_illuminance_activated_entity.yaml
    input:
      motion_sensor: binary_sensor.garage_motion_occupancy
      target_entity: switch.garage_overhead_light
      no_motion_wait: '4'
- id: '1659286961861'
  alias: "[\U0001F4E3] Notify when garage door was left open for too long (TTS Only)"
  description: ''
  trigger:
  - platform: state
    entity_id:
    - timer.garage_door
    to: open
    for:
      minutes: 15
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.garage_door
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: tts.google_translate_say
    data:
      message: Garage door has been open for 15 minutes.
      entity_id: media_player.indoor_speakers
  - service: timer.start
    data:
      duration: '15'
    target:
      entity_id: timer.garage_door
