camera:
- platform: reolink_dev
  host: !secret Camera_Front_Host
  username: !secret Camera_User
  password: !secret Camera_Password
  name: frontdoor #(optional, default Reolink Camera)
  stream: main #(optional, default main)
  protocol: rtmp #(optional, default rtmp)
  channel: 0 #(optional, default 0)
  scan_interval: 5 #(optional, default 30s)

binary_sensor:
  platform: template
  sensors:
    motion_frontdoor:
      friendly_name: Camera frontdoor
      device_class: motion
      value_template: "{{ is_state('camera.frontdoor', 'motion') }}"
      delay_off: 
          seconds: 30

switch:
  - platform: template
    switches:
      camera_frontdoor_email:
        value_template: "{{ is_state_attr('camera.frontdoor', 'email_enabled', true) }}"
        turn_on:
          service: camera.enable_email
          data:
            entity_id: camera.frontdoor
        turn_off:
          service: camera.disable_email
          data:
            entity_id: camera.frontdoor
        icon_template: >-
          {% if is_state_attr('camera.frontdoor', 'email_enabled', true) %}
            mdi:email
          {% else %}
            mdi:email-outline
          {% endif %}
            
      camera_frontdoor_ftp:
        value_template: "{{ is_state_attr('camera.frontdoor', 'ftp_enabled', true) }}"
        turn_on:
          service: camera.enable_ftp
          data:
            entity_id: camera.frontdoor
        turn_off:
          service: camera.disable_ftp
          data:
            entity_id: camera.frontdoor
        icon_template: >-
          {% if is_state_attr('camera.frontdoor', 'ftp_enabled', true) %}
            mdi:filmstrip
          {% else %}
            mdi:filmstrip-off
          {% endif %}
          
      camera_frontdoor_ir_lights:
        value_template: "{{ is_state_attr('camera.frontdoor', 'ir_lights_enabled', true) }}"
        turn_on:
          service: camera.enable_ir_lights
          data:
            entity_id: camera.frontdoor
        turn_off:
          service: camera.disable_ir_lights
          data:
            entity_id: camera.frontdoor
        icon_template: >-
          {% if is_state_attr('camera.frontdoor', 'ir_lights_enabled', true) %}
            mdi:flashlight
          {% else %}
            mdi:flashlight-off
          {% endif %}

      camera_frontdoor_motion_detection:
        value_template: "{{ is_state_attr('camera.frontdoor', 'motion_detection_enabled', true) }}"
        turn_on:
          service: camera.enable_motion_detection
          data:
            entity_id: camera.frontdoor
        turn_off:
          service: camera.disable_motion_detection
          data:
            entity_id: camera.frontdoor
        icon_template: >-
          {% if is_state_attr('camera.frontdoor', 'motion_detection_enabled', true) %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}
